// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGfkwRfbfmyudRyzt5ZkRcpo0PHKY_igQ',
    appId: '1:1052814150:web:c85a580c8d86d71f581347',
    messagingSenderId: '1052814150',
    projectId: 'flutterpro-abd6a',
    authDomain: 'flutterpro-abd6a.firebaseapp.com',
    storageBucket: 'flutterpro-abd6a.firebasestorage.app',
    measurementId: 'G-K02EQVS6PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSGDhObuoJiNZnUzoX9G_BU4uQ7OflO58',
    appId: '1:1052814150:android:6b0d0cff46d06bb3581347',
    messagingSenderId: '1052814150',
    projectId: 'flutterpro-abd6a',
    storageBucket: 'flutterpro-abd6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2wUdy109YRe9OjqqJp0Wc3p_cvQM8_LI',
    appId: '1:1052814150:ios:19b8714dd573e13c581347',
    messagingSenderId: '1052814150',
    projectId: 'flutterpro-abd6a',
    storageBucket: 'flutterpro-abd6a.firebasestorage.app',
    iosBundleId: 'com.example.qwe',
  );

}